apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-generator
  labels:
    app: event-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-generator
  template:
    metadata:
      labels:
        app: event-generator
    spec:
      containers:
        - name: event-generator
          image: liveklass-event-generator:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: event-generator-config
            - secretRef:
                name: event-generator-secret
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: app-logs
          persistentVolumeClaim:
            claimName: event-generator-logs-pvc
