apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-generator-logs-pvc
  labels:
    app: event-generator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
